# Generated by Django 4.1.7 on 2023-05-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id_animal', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('macho', 'macho'), ('fêmea', 'fêmea')], max_length=6)),
                ('idade', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('condicao_de_saude', models.CharField(choices=[('saudável', 'saudável'), ('ferido', 'ferido'), ('doente', 'doente')], max_length=9)),
                ('esterilizado', models.CharField(choices=[('sim', 'sim'), ('não', 'não')], max_length=3)),
                ('data_ultimo_atendimento', models.DateField()),
                ('endereco', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('idClinica', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=45)),
                ('CNPJ', models.CharField(max_length=14)),
                ('medicoResp', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_Veterinario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('CRMV', models.IntegerField()),
                ('celular', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('idClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('id_animal', models.IntegerField()),
                ('Funcao', models.CharField(max_length=45)),
                ('Nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('idAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animais')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('idServicos', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Petshop', models.CharField(max_length=45)),
                ('AnimaisPerdidos', models.CharField(max_length=45)),
                ('LarTemporario', models.CharField(max_length=45)),
                ('Voluntarios', models.CharField(max_length=45)),
                ('larDefinitivo', models.CharField(max_length=45)),
                ('DoadoresRecurso', models.CharField(max_length=45)),
                ('TaxiDog', models.CharField(max_length=45)),
                ('ServVeterinaio', models.CharField(max_length=45)),
                ('idClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Ongs',
            fields=[
                ('idOngs', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('RazaoSocial', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('resp', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=45)),
                ('CNPJ', models.CharField(max_length=45)),
                ('endereco', models.CharField(max_length=45)),
                ('idAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.animais')),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('idLocalizacao', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('logradouro', models.CharField(max_length=45)),
                ('numero', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=45)),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('Localizacaocol', models.CharField(max_length=45)),
                ('idClinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.clinica')),
            ],
        ),
        migrations.CreateModel(
            name='LarTemporario',
            fields=[
                ('idLarTemporario', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Tutor', models.CharField(max_length=45)),
                ('voluntario', models.CharField(max_length=45)),
                ('PetShop', models.CharField(max_length=45)),
                ('ClinicaVeterinaria', models.CharField(max_length=45)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LarDefinitivo',
            fields=[
                ('idLarDefinitivo', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Funcao', models.CharField(max_length=45)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='clinica',
            name='idServicos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.servicos'),
        ),
        migrations.AddField(
            model_name='animais',
            name='idLarDefinitivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.lardefinitivo'),
        ),
        migrations.AddField(
            model_name='animais',
            name='idLarTemporario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.lartemporario'),
        ),
        migrations.AddField(
            model_name='animais',
            name='idLocalizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.localizacao'),
        ),
    ]
